force-app/main/default/objects/Account/fields/DBA_Name__c.field-meta.xml
<CustomField>
    <fullName>DBA_Name__c</fullName>
    <label>DBA Name</label>
    <type>Text</type>
    <length>80</length>
</CustomField>

force-app/main/default/objects/Account/fields/QuickBooks_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>QuickBooks_Customer_Id__c</fullName>
    <label>QuickBooks Customer Id</label>
    <type>Text</type>
    <length>30</length>
    <externalId>true</externalId>
</CustomField>

force-app/main/default/objects/Account/fields/QuickBooks_Customer_SyncToken__c.field-meta.xml
<CustomField>
    <fullName>QuickBooks_Customer_SyncToken__c</fullName>
    <label>QuickBooks Customer SyncToken</label>
    <type>Text</type>
    <length>10</length>
</CustomField>

force-app/main/default/objects/Account/fields/QuickBooks_Email__c.field-meta.xml
<CustomField>
    <fullName>QuickBooks_Email__c</fullName>
    <label>QuickBooks Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/QuickBooksCustomerSyncBatch.cls
public with sharing class QuickBooksCustomerSyncBatch implements Database.Batchable<SObject>, Database.AllowsCallouts {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
            SELECT Id, DBA_Name__c, QuickBooks_Email__c,
                BillingStreet, BillingCity, BillingState, BillingPostalCode,
                QuickBooks_Customer_Id__c, QuickBooks_Customer_SyncToken__c
            FROM Account WHERE Type = 'Customer'
        ]);
    }
    public void execute(Database.BatchableContext bc, List<Account> scope) {
        for (Account acct : scope) {
            QuickBooksService.createOrUpdateCustomer(acct);
        }
    }
    public void finish(Database.BatchableContext bc) {}
}